GAMEPAD_UP = $10
GAMEPAD_DOWN = $20
GAMEPAD_LEFT = $40
GAMEPAD_RIGHT = $80
GAMEPAD_A = $01
GAMEPAD_B = $02
GAMEPAD_SELECT = $04
GAMEPAD_START = $08

GAMEPAD_HORI = $C0
GAMEPAD_VERT = $30
GAMEPAD_MOVE = $F0

GAMEPAD_AB = $03

GAMEPAD_CONFIRM = $09

gamepad 		.rs 1
gamepadLast 	.rs 1
gamepadPressed 	.rs 1
